"""Add Post field uuid

Revision ID: b7549f3aa7e5
Revises: 5734699c44b5
Create Date: 2022-07-18 12:41:15.258189

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b7549f3aa7e5'
down_revision = '5734699c44b5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('user_id', postgresql.UUID(), nullable=True))
    op.create_foreign_key(None, 'post', 'user', ['user_id'], ['uuid'], onupdate='CASCADE', ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.alter_column('post', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.drop_column('post', 'user_id')
    # ### end Alembic commands ###
